# Generated by Django 3.2.8 on 2021-10-27 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=500)),
                ('year', models.IntegerField()),
                ('section', models.CharField(choices=[['Experience', 'Experience'], ['Education', 'Education'], ['Volunteering', 'Volunteering']], max_length=500, null=True)),
                ('active', models.BooleanField(default=False)),
                ('place', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Resumes',
            },
        ),
        migrations.AlterField(
            model_name='projects',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 17, 5, 55, 560489)),
        ),
    ]
