# Generated by Django 3.2.8 on 2021-10-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211017_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='brief_describe',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
