# Generated by Django 3.2.8 on 2021-10-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_brief_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='brief_describe',
            field=models.CharField(max_length=100, null=True, verbose_name='Description'),
        ),
    ]
