# Generated by Django 3.2.8 on 2021-10-17 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 7, 24, 3, 340849)),
        ),
        migrations.AddField(
            model_name='projects',
            name='team',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
