# Generated by Django 3.2.8 on 2021-10-17 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211017_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 7, 26, 43, 379339)),
        ),
    ]
