# Generated by Django 3.2.8 on 2021-10-24 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_projects_finish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 20, 2, 6, 69742)),
        ),
    ]
