# Generated by Django 3.2.8 on 2021-10-25 21:18

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0014_auto_20211025_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='repos',
        ),
        migrations.AddField(
            model_name='projects',
            name='level',
            field=models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('huge', 'huge')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 23, 18, 8, 564732)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='participated', to=settings.AUTH_USER_MODEL),
        ),
    ]
