# Generated by Django 3.2.8 on 2021-10-25 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20211025_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 23, 18, 45, 731058)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='level',
            field=models.CharField(choices=[('small2', 'small'), ('medium2', 'medium'), ('huge2', 'huge')], max_length=500, null=True),
        ),
    ]
